
#' Extract trade summary from CME Market by Price data
#'
#' `trade_summary()` extracts the trade summary messages from the whole CME
#' Market by Price (MBP) datasets, including timestamps, trade price, trade
#' quantity, sequence number, number of orders involved in a trade, etc.
#'
#' @param mbp_input Market by Price raw data.
#' @param date Trading date associated with the raw data, which can be found in
#' the file name easily in \code{YYYYMMDD} format. This argument is required to select
#' the parsing format.
#' @param price_displayformat Display format of trade price, which could be 1,
#' 0.01, or 0.001, etc. If it is unknown, the nearest Sunday's (not a CME trading
#' holiday) MBP/MBO data need to be provided to extract the display format.
#' @param sunday_input When \code{price_displayformat} is not provided, the nearest
#' Sunday's (not a CME trading holiday)
#' MBP/MBO data need to be provided to extract the price display format.
#'
#' @returns A list of data.table that contains trade summary for all tradeable
#' contracts in a trading day.
#' @seealso [meta_data()]
#' @export
#'
#' @import data.table stringr
#'
#' @section Trade summary:
#' In terms of trade summary, all trades are recorded with specific message tags.
#' Each trade is timestamped to nanosecond and a unique sequence number is also assigned if multiple
#' trades occur with the same timestamps. Trade price and quantity executed are recorded
#' for each trade. The number of orders include all matching (limit) orders and an incoming (market) order.
#' When implied orders are matched, the number of orders do not contain these implied orders as the CME
#' does not stipulate it. CME disseminates the trade aggressor for each trade, with 1 indicating buyer-initiated
#' trades, and 2 seller-initiated trades. A trade aggressor might not be defined when a trade involves implied trades, which is
#' coded as 0 by the CME.
#' More details can refer to \url{https://cmegroupclientsite.atlassian.net/wiki/spaces/EPICSANDBOX/pages/457418925/MDP+3.0+-+Trade+Summary}.
#'
#' @section Fields of trade summary:
#' \itemize{
#' \item Date: Trading date. The night trading session on Sundays is assigned
#' the trading date as the next Monday.
#' \item MsgSeq: Message sequence number for each packaet. This is unique for every
#' message, however, it is not security unique.
#' \item SendingTime: The timestamp (in UTC) indicates the time when outbound messages to clients
#' leave the segment gateway (Tag 60).
#' \item TransactTime: The timestamp (in UTC) indicates the time when incoming messages hit the segment gateway (Tag 52).
#' \item Code: Contract symbol.
#' \item Seq: Sequence number, which is security unique. A single packaet may contain information
#' for multiple tradeable contracts with the single message sequence number, while every
#' tradeable contract has its unique sequence number.
#' \item PX: Trade price.
#' \item Size: Trade size displayed as the number of contracts.
#' \item Ord: Number of orders involved in a trade, including both matching (limit) order and an incoming (market) order.
#' \item agg: Trade aggressor generated by the CME. 1 indicates buyer-initiated trades,
#' 2 indicates seller-initiated trades, while 0 indicates no trade aggressor is defined.
#'}
#'
#'
#' @examples
#' # This function requires a CME data license to run
#' # Example showing how to extract trade summary
#' # extract trade summary
#' # Know the display format of trade price
#' \dontrun{
#' trades <- trade_summary(file, "2019-01-07", price_displayformat = 1)
#'
#' # Unknown price_displayformat
#' trades <- trade_summary(file, "2019-01-07", sunday_input = sunday_file)
#' }
trade_summary <- function(mbp_input, date, price_displayformat=NULL, sunday_input=NULL){

  Code <- Seq <- PX <- DisplayFactor <- NULL

  date <- as.Date(date)

  if(inherits(date, "Date")==FALSE){

    stop("date should be in the format as YYYY-MM-DD.")

  }
  data <-  fread(mbp_input, header = F, sep="\\", fill=TRUE)[[1L]]

  ### checking the price display factor


  if(date < "2015-11-20"){

    Index <- str_subset(data, "\001269=2")
    Index <- str_replace_all(Index, "\001",",")
    Trade <- str_replace_all(Index,",269=2,",",")

    rm(Index)
    rm(data)

    ## delete the tags that are not necessary

    Trade <-  str_replace_all(Trade, "1128=([^,]*),9=([^,]*),35=([^,]*),49=([^,]*),", "")
    Trade <-  str_replace_all(Trade, ",5799=([^,]*),", ",")
    Trade <-  str_replace_all(Trade, ",268=([^,]*),", ",")
    Trade <-  str_replace_all(Trade, ",279=([^,]*),", ",")
    Trade <-  str_replace_all(Trade, ",22=([^,]*),", ",")
    Trade <-  str_replace_all(Trade, ",48=([^,]*),", ",")
    Trade <-  str_replace_all(Trade, ",273=([^,]*),", ",")
    Trade <-  str_replace_all(Trade, ",274=([^,]*),", ",")
    Trade <-  str_replace_all(Trade, ",451=([^,]*),", ",")
    Trade <-  str_replace_all(Trade, ",1020=([^,]*),", ",")



    ## searching for the following tags,
    ## tag52-time stamp
    ## tag75-date
    #  tag83-seq#
    #  tag107-contract
    #  tag269-type: 2-trade
    #  tag270-px
    #  tag271-qty

    ## generate the trade data (with order flow)
    ## first find the tag269=2
    ## Trade summary pattern
    ## 75 60 269=2 55 270 271 346 5797 37711-trade id 37705 37 32

    if(length(Trade)!=0){

      ## generate the trade data (without order flow)
      trade <- str_match_all(Trade, "83=([^,]*),107=([^,]*),270=([^,]*),271=([^,]*),1003=([^,]*),5797=([^,]*),")
      n_row <- sapply(trade, nrow)
      trade.info <- unlist(str_extract_all(Trade,"34=([^,]*),52=([^,]*),75=([^,]*),"))
      trade.info <- str_dup(trade.info, n_row)
      trade <- as.data.table(do.call(rbind, trade))[,-1]
      names(trade)[c(1:6)] <- c("Seq","Code","PX", "Size","TrdID","agg")

      trade.info <- str_match_all(trade.info, "34=([^,]*),52=([^,]*),75=([^,]*),")
      trade.info <- as.data.table(do.call(rbind,trade.info))[,-1]
      names(trade.info)[c(1:3)] <- c("MsgSeq","SendingTime","Date")

      trade.info$Date <- as.Date(trade.info$Date, "%Y%m%d")
      #Time <- paste(substr(trade.info$Time,1,8),substr(trade.info$Time,9,10),substr(trade.info$Time,11,12),
      #substr(trade.info$Time,13,14),substr(trade.info$Time,15,23),sep=".")
      #trade.info$Time <- as.POSIXct(Time, tz="UTC", "%Y%m%d.%H.%M.%OS") ## original time is UTC
      #attr(trade.info$Time, "tzone") <- "America/Chicago" ## US central time
      #trade$MsgSeq <- as.numeric(trade$MsgSeq)
      trade$Seq <- as.numeric(trade$Seq)
      trade$PX <- as.numeric(trade$PX)
      trade$Size <- as.numeric(trade$Size)

      trade <- cbind(trade.info, trade)
      rm(trade.info)

      ###

      trade1 <- str_match_all(Trade, "83=([^,]*),107=([^,]*),270=([^,]*),271=([^,]*),1003=([^,]*),")
      n_row <- sapply(trade1, nrow)
      trade.info1 <- unlist(str_extract_all(Trade,"34=([^,]*),52=([^,]*),75=([^,]*),"))
      trade.info1 <- str_dup(trade.info1, n_row)
      trade1 <- as.data.table(do.call(rbind, trade1))[,-1]
      names(trade1)[c(1:5)] <- c("Seq","Code","PX", "Size","TrdID")

      trade.info1 <- str_match_all(trade.info1, "34=([^,]*),52=([^,]*),75=([^,]*),")
      trade.info1 <- as.data.table(do.call(rbind,trade.info1))[,-1]
      names(trade.info1)[c(1:3)] <- c("MsgSeq","SendingTime","Date")

      trade.info1$Date <- as.Date(trade.info1$Date, "%Y%m%d")
      #Time <- paste(substr(trade.info$Time,1,8),substr(trade.info$Time,9,10),substr(trade.info$Time,11,12),
      #substr(trade.info$Time,13,14),substr(trade.info$Time,15,23),sep=".")
      #trade.info$Time <- as.POSIXct(Time, tz="UTC", "%Y%m%d.%H.%M.%OS") ## original time is UTC
      #attr(trade.info$Time, "tzone") <- "America/Chicago" ## US central time
      #trade$MsgSeq <- as.numeric(trade$MsgSeq)
      trade1$Seq <- as.numeric(trade1$Seq)
      trade1$PX <- as.numeric(trade1$PX)
      trade1$Size <- as.numeric(trade1$Size)

      trade1 <- cbind(trade.info1, trade1)
      rm(trade.info1)

      trade1.1 <- trade[, -"agg"]

      trade1 <- rbind(trade1.1, trade1)

      trade1 <- unique(trade1)

      trade <- merge(trade1, trade[, c("Seq", "Code", "agg")], by=c("Seq", "Code"), all=TRUE)
      setkey(trade, Code, Seq)

      rm(trade1.1, trade1)


      trade2 <- str_match_all(Trade, "83=([^,]*),107=([^,]*),270=([^,]*),271=([^,]*),277=([^,]*),1003=([^,]*),5797=([^,]*),")
      n_row <- sapply(trade2, nrow)
      trade.info2 <- unlist(str_extract_all(Trade,"34=([^,]*),52=([^,]*),75=([^,]*),"))
      trade.info2 <- str_dup(trade.info2, n_row)
      trade2 <- as.data.table(do.call(rbind, trade2))[,-1]
      names(trade2)[c(1:7)] <- c("Seq","Code","PX","Size","TrdCon","TrdID","agg")

      trade.info2 <- str_match_all(trade.info2, "34=([^,]*),52=([^,]*),75=([^,]*),")
      trade.info2 <- as.data.table(do.call(rbind,trade.info2))[,-1]
      names(trade.info2)[c(1:3)] <- c("MsgSeq","SendingTime","Date")

      trade.info2$Date <- as.Date(trade.info2$Date, "%Y%m%d")
      #Time <- paste(substr(trade.info$Time,1,8),substr(trade.info$Time,9,10),substr(trade.info$Time,11,12),
      #substr(trade.info$Time,13,14),substr(trade.info$Time,15,23),sep=".")
      #trade.info$Time <- as.POSIXct(Time, tz="UTC", "%Y%m%d.%H.%M.%OS") ## original time is UTC
      #attr(trade.info$Time, "tzone") <- "America/Chicago" ## US central time
      #trade$MsgSeq <- as.numeric(trade$MsgSeq)
      trade2$Seq <- as.numeric(trade2$Seq)
      trade2$PX <- as.numeric(trade2$PX)
      trade2$Size <- as.numeric(trade2$Size)

      trade2 <- cbind(trade.info2, trade2)
      rm( trade.info2)

      ## special trades

      trade3 <- str_match_all(Trade, "83=([^,]*),107=([^,]*),270=([^,]*),271=([^,]*),277=([^,]*),1003=([^,]*),")
      n_row <- sapply(trade3, nrow)
      trade.info3 <- unlist(str_extract_all(Trade,"34=([^,]*),52=([^,]*),75=([^,]*),"))
      trade.info3 <- str_dup(trade.info3, n_row)
      trade3 <- as.data.table(do.call(rbind, trade3))[,-1]
      names(trade3)[c(1:6)] <- c("Seq","Code","PX","Size","TrdCon","TrdID")

      trade.info3 <- str_match_all(trade.info3, "34=([^,]*),52=([^,]*),75=([^,]*),")
      trade.info3 <- as.data.table(do.call(rbind,trade.info3))[,-1]
      names(trade.info3)[c(1:3)] <- c("MsgSeq","SendingTime","Date")

      trade.info3$Date <- as.Date(trade.info3$Date, "%Y%m%d")
      #Time <- paste(substr(trade.info$Time,1,8),substr(trade.info$Time,9,10),substr(trade.info$Time,11,12),
      #substr(trade.info$Time,13,14),substr(trade.info$Time,15,23),sep=".")
      #trade.info$Time <- as.POSIXct(Time, tz="UTC", "%Y%m%d.%H.%M.%OS") ## original time is UTC
      #attr(trade.info$Time, "tzone") <- "America/Chicago" ## US central time
      #trade$MsgSeq <- as.numeric(trade$MsgSeq)
      trade3$Seq <- as.numeric(trade3$Seq)
      trade3$PX <- as.numeric(trade3$PX)
      trade3$Size <- as.numeric(trade3$Size)

      trade3 <- cbind(trade.info3, trade3)
      rm(trade.info3)

      trade2.2 <- trade2[, -c("agg")]

      trade2_3_all <- rbind(trade2.2, trade3)

      trade2_3_all <- unique(trade2_3_all)

      trade2_3_all <- merge(trade2[, c("Code", "Seq", "agg")], trade2_3_all, by=c( "Code","Seq"), all=TRUE)

      setkey(trade2_3_all, Code, Seq)


      trade <- rbind(trade, trade2_3_all, fill=TRUE)

      setkey(trade, Code, Seq)
      setcolorder(trade, c("Date", "MsgSeq", "SendingTime", "Code", "Seq", "PX", "Size", "agg"))


    }
  }  else{


    Index <- str_subset(data, "\001269=2")
    Index <- str_replace_all(Index, "\001",",")
    Trade <- str_replace_all(Index,",269=2,",",")
    rm(Index)

    rm(data)

    ## delete the tags that are not necessary

    Trade <- str_replace_all(Trade, "1128=([^,]*),9=([^,]*),35=([^,]*),49=([^,]*),","")
    Trade <- str_replace_all(Trade, ",5799=([^,]*),",",")
    Trade <- str_replace_all(Trade, ",268=([^,]*),",",")
    Trade <- str_replace_all(Trade, ",279=([^,]*),",",")
    Trade <- str_replace_all(Trade, ",48=([^,]*),",",")
    Trade <- str_replace_all(Trade, ",37705=([^,]*),",",")
    Trade <- str_replace_all(Trade, "37=([^,]*),","")
    Trade <- str_replace_all(Trade, "32=([^,]*),","")

    ## searching for the following tags,
    ## tag52-time stamp
    ## tag75-date
    #  tag83-seq#
    #  tag55-contract
    #  tag269-type: 2-trade
    #  tag270-px
    #  tag271-qty
    #  tag346-# of orders in a given px level
    #  tag5797-buyer/seller initiated
    #  tag33705-order entries

    ## generate the trade data (with order flow)
    ## consider the tradings with both specific defined aggressors or non-defined aggressors (implied order or sides are not defined)
    ## tag5797=0 or tag5797=1 or tag5797=2
    ## first find the tag269=2
    ## Trade summary pattern
    ## 75 60 269=2 55 270 271 346 5797 37711-trade id 37705 37 32


    if(length(Trade)!=0){

      ## generate the trade data (without order flow)
      trade <- str_match_all(Trade, "55=([^,]*),83=([^,]*),270=([^,]*),271=([^,]*),346=([^,]*),5797=([^,]*)")
      n_row <- sapply(trade, nrow)
      trade.info <- unlist(str_extract_all(Trade,"75=([^,]*),34=([^,]*),52=([^,]*),60=([^,]*),"))
      trade.info <- str_dup(trade.info, n_row)
      trade <- as.data.table(do.call(rbind, trade))[,-1]
      names(trade)[c(1:6)] <- c("Code","Seq","PX","Size","Ord","agg")

      trade.info <- str_match_all(trade.info, "75=([^,]*),34=([^,]*),52=([^,]*),60=([^,]*),")
      trade.info <- as.data.table(do.call(rbind,trade.info))[,-1]
      names(trade.info)[c(1:4)] <- c("Date","MsgSeq","SendingTime", "TransactTime")

      trade.info$Date <- as.Date(trade.info$Date, "%Y%m%d")
      #Time <- paste(substr(trade.info$Time,1,8),substr(trade.info$Time,9,10),substr(trade.info$Time,11,12),
       #             substr(trade.info$Time,13,14),substr(trade.info$Time,15,23),sep=".")
      #trade.info$Time <- as.POSIXct(Time, tz="UTC", "%Y%m%d.%H.%M.%OS") ## original time is UTC
      #attr(trade.info$Time, "tzone") <- "America/Chicago" ## US central time
      #trade$MsgSeq <- as.numeric(trade$MsgSeq)
      trade$Seq <- as.numeric(trade$Seq)

      trade$PX <- as.numeric(trade$PX)
      trade$Size <- as.numeric(trade$Size)
      trade$Ord <- as.numeric(trade$Ord)
      trade$agg <- as.numeric(trade$agg)

      trade <- cbind(trade.info, trade)
      trade$MsgSeq <- as.numeric(trade$MsgSeq)
      setkey(trade, Code, Seq)
      setcolorder(trade, c("Date", "MsgSeq", "SendingTime", "TransactTime","Code", "Seq", "PX", "Size","Ord", "agg"))
    }

    }

  results <- split(trade, by="Code")

  if(is.null(price_displayformat)){

    if(is.null(sunday_input)){

      stop("Sunday's security definition at the same week must be provided to get the price display format")
    }

    definition <- meta_data(sunday_input, date=date)

    setnames(definition, "Symbol", "Code")

    definition <- definition[Code %in% names(results)]

    results <- lapply(results, function(x) {
      x[, PX := PX * definition[Code == unique(x$Code), as.numeric(DisplayFactor) ]]
      return(x)
    })



  }else{

   results <- lapply(results, function(x) x[, grep("PX", colnames(x)):=lapply(.SD, function(x) as.numeric(x)*as.numeric(price_displayformat)), .SDcols = patterns("PX")])

  }

  cat("CME MDP 3.0 Trade Summary", "\n",
      "contracts:", names(results))
  return(results)
}


